Add favicons for API Tools project
laminas/getlaminas.org pull request #138
Opened 2023-04-03 11:57 UTC by Arhell

|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes
| RFC           | yes/no
| QA            | yes/no

### Description

add icons for https://api-tools.getlaminas.org/

2023-04-19 11:21 UTC, Arhell reviewed
@froschdesign take a look please

2023-04-26 18:45 UTC, froschdesign requested changes
I don't know exactly if we really need the configuration and webmanifest files, but the file names they contain are incorrect.

2023-04-26 18:45 UTC, froschdesign commented on public/images/favicon/api-tools/site.webmanifest
> +            "src": "/images/favicon/api-tools/aandroid-chrome-512x512.png",
The file name is wrong here.

2023-04-26 18:45 UTC, froschdesign commented on public/images/favicon/api-tools/browserconfig.xml
> +            <wide310x150logo src="/images/img/favicon/api-tools/amstile-310x150.png"/>
The same here.

2023-04-27 10:18 UTC, Arhell commented
@froschdesign done

2023-05-28 10:30 UTC, Arhell commented
@froschdesign

2023-06-07 06:41 UTC, froschdesign approved these changes

2023-06-07 06:41 UTC, merged

2023-06-07 06:41 UTC, froschdesign commented
@Arhell 
Thank you for your time and this contribution! 👍