new design for homepage
laminas/getlaminas.org pull request #202
Opened 2024-08-22 15:08 UTC by Jurj-Bogdan

|    Q          |   A
|-------------- | ------
| New Feature   | yes
| RFC           | yes

### Description

An initial step in implementing the new homepage design, as discussed in #162. Added the "sponsor" and "popular projects" sections suggested in the comments, albeit on a white background for logo visibility.

Open to any suggestions/changes going forward with the issue at hand

2024-08-22 16:18 UTC, arhimede commented
Preview here:
https://preview-lf246gy-2ja7ciew2nbkm.us-2.platformsh.site/

2024-08-22 18:09 UTC, froschdesign requested changes
A good first step.

2024-08-22 18:09 UTC, froschdesign commented on config/autoload/home-page-content.global.php
> +            'logo' => '/images/sponsors/drupal.png',
The Drupal logo should also contain the wordmark: https://www.drupal.org/about/media-kit/logos

2024-08-22 18:09 UTC, froschdesign commented on config/autoload/home-page-content.global.php
> +            'logo' => '/images/sponsors/magento.png',
The Magento logo should also contain the name for better identification.

2024-08-24 16:06 UTC, arhimede commented
preview updated 
https://preview-lf246gy-2ja7ciew2nbkm.us-2.platformsh.site/

2024-09-03 07:24 UTC, froschdesign commented
@weierophinney 
Do you see any legal problems? I remember that this was once a topic.

2024-10-07 20:04 UTC, weierophinney commented
@froschdesign Nothing leaps out as problematic to me. :ship:

2024-10-07 20:05 UTC, froschdesign approved these changes

2024-10-08 09:09 UTC, merged